# Site settings
name: Abhishek C
title: Abhishek C | Front End Software Engineer
description: Design-minded front-end software engineer focused on building beautiful interfaces and experiences
url: https://abhi1401.github.io/
baseurl: ''
email: abhishek.mvr@outlook.com
cover: https://abhi1401.github.io/img/og.png
logo: https://abhi1401.github.io/img/emojis/technologist.png
resume: https://abhi1401.github.io/resume.pdf
social:
  - title: email
    url: mailto:abhishek.mvr@outlook.com
  - title: twitter
    url: https://twitter.com/abhi1401
  - title: instagram
    url: https://instagram.com/abhi1401
  - title: codepen
    url: http://codepen.io/abhi1401
  - title: github
    url: https://github.com/abhi1401
  - title: linkedin
    url: https://www.linkedin.com/in/abhi1401

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
